import type { NextPage } from 'next'
import Link from 'next/link'
import Head from 'next/head'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col items-center p-5 space-y-5">
        <h1 className="text-4xl">Examples</h1>
        <ul>
          <li>Clickable</li>
        </ul>
        <h2 className="text-lg">
          For testing schema, go to{' '}
          <Link href="/schema">
            <a className="text-blue-600">/schema</a>
          </Link>
        </h2>
      </main>
    </div>
  )
}

export default Home
